### ISSUE TITLE
Cannot find Widget of Undefined

### ISSUE THREAD

**Issue by wirsingj** [xolvio/chimp-widgets#5]
I am trying to get the widgets working-   I have both Chimp and chimp-widgets installed globally...  my widget file looks like:

```
module.exports = function(){
    this.Before(function(done){
        this.SearchPage = this.widgets.Widget.extend({
            selector: '#searchform',
            searchFor: function(query){
              this.setValue('input[name="q"]', searchTerm);
              this.keys(['Enter']);
            }

        });
        this.SearchPage.url = 'www.google.com';
        done();
    });
};
```

When I run chimp I get the error:   

```
TypeError: Cannot read property 'Widget' of undefined
  at World.<anonymous> (features/support/widgets.js:3:39)
```

**Comment by SamHatoum** [comment]
I just pushed 0.3.0 - try with that then let us know

**Comment by wirsingj** [comment]
I installed it again through NPM, both globally and locally, and still no luck.  

I'm not really sure of how Chimp is interacting with chimp-widgets, but seems like it cannot find it.

**Comment by tikolakin** [comment]
Hi @samhatoum , I have experienced the same issue on 0.3.0

**Comment by LewisW** [comment]
I believe the latest version of chimp.js assigns the variable to `this.chimpWidgets` [as you can see here](https://github.com/xolvio/chimp/blob/68bb1bf8b53bcdfef97f65a4df8cbf91b282fde0/lib/cucumberjs/world.js#L20).

The chimp widgets documentation is a bit out of date, I'll update it to add a migration guide to the latest chimp.js changes and the move over to asynchronous.

**Comment by leabaertschi** [comment]
I'm having the same issue. I checked the line that you mentioned @LewisW, the thing is that `global.chimpWidgets` is `undefined` at runtime. Any idea why? I'm using chimp-widgets version 0.3.0 and chimp version 0.44.0
For a quick fix just add the following line to your World function:
`this.chimpWidgets = require('chimp-widgets');`

**Comment by joscha** [comment]
I think https://github.com/xolvio/chimp/issues/333 might be the reason
